/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { hostname$_T } from './hostname$_b'
import type { pathname$_T } from './pathname$_b'
import type { window_location$_T } from './window_location$_b'
import type { window_location_hostname$_T } from './window_location_hostname$_b'
import type { window_location_pathname_T } from './window_location_pathname_b'
export interface window_ctx_I {
	hostname$?:hostname$_T
	pathname$?:pathname$_T
	window_location$?:window_location$_T
	window_location_hostname$?:window_location_hostname$_T
	window_location_pathname?:window_location_pathname_T
}