/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { hostname$_T } from './hostname$_b.js'
import type { pathname$_T } from './pathname$_b.js'
import type { window_location$_T } from './window_location$_b.js'
import type { window_location_hostname$_T } from './window_location_hostname$_b.js'
import type { window_location_pathname$_T } from './window_location_pathname$_b.js'
export interface window_ctx_I {
	hostname$?:hostname$_T
	pathname$?:pathname$_T
	window_location$?:window_location$_T
	window_location_hostname$?:window_location_hostname$_T
	window_location_pathname$?:window_location_pathname$_T
}