/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import { be_ } from '@ctx-core/object'
import type { B } from '@ctx-core/object'
import type { hostname_T } from './hostname_b'
import { hostname_b } from './hostname_b'
import type { pathname_T } from './pathname_b'
import { pathname_b } from './pathname_b'
import type { window_location_T } from './window_location_b'
import { window_location_b } from './window_location_b'
import type { window_location_hostname_T } from './window_location_hostname_b'
import { window_location_hostname_b } from './window_location_hostname_b'
import type { window_location_pathname_T } from './window_location_pathname_b'
import { window_location_pathname_b } from './window_location_pathname_b'
export interface window_ctx_I {
	hostname?:hostname_T
	pathname?:pathname_T
	window_location?:window_location_T
	window_location_hostname?:window_location_hostname_T
	window_location_pathname?:window_location_pathname_T
	window_b_h?:window_b_h_T
}
export interface window_b_h_T {
	get hostname():hostname_T
	get pathname():pathname_T
	get window_location():window_location_T
	get window_location_hostname():window_location_hostname_T
	get window_location_pathname():window_location_pathname_T
}
export function window_b_h_b(ctx:window_ctx_I):B<window_ctx_I, 'window_b_h'> {
	return be_('window_b_h', ()=>{
		return {
			get hostname() { return hostname_b(ctx) },
			get pathname() { return pathname_b(ctx) },
			get window_location() { return window_location_b(ctx) },
			get window_location_hostname() { return window_location_hostname_b(ctx) },
			get window_location_pathname() { return window_location_pathname_b(ctx) }
		}
	})
}
